#include <sys.h>
#include <Pulley_VEHICLE.h>

u8 Pulley_VEHICLE_A_State;
u8 Pulley_VEHICLE_B_State;
u8 Pulley_VEHICLE_C_State;
u8 Pulley_VEHICLE_A_ServoAngle;
u8 Pulley_VEHICLE_B_ServoAngle;
u8 Pulley_VEHICLE_C_Servo_1_Angle;
u8 Pulley_VEHICLE_C_Servo_2_Angle;

void Pulley_VEHICLE_Init()
{
    //Reset servo
    Pulley_SERVO_Write(PULLEY_VEHICLE_A_SERVO, PULLEY_VEHICLE_A_SERVO_DEFANG);
    Pulley_SERVO_Write(PULLEY_VEHICLE_B_SERVO, PULLEY_VEHICLE_B_SERVO_DEFANG);
    Pulley_SERVO_Write(PULLEY_VEHICLE_C_SERVO_1, PULLEY_VEHICLE_C_SERVO_1_DEFANG);
    Pulley_SERVO_Write(PULLEY_VEHICLE_C_SERVO_2, PULLEY_VEHICLE_C_SERVO_2_DEFANG);
    Pulley_VEHICLE_A_ServoAngle = PULLEY_VEHICLE_A_SERVO_DEFANG;
    Pulley_VEHICLE_B_ServoAngle = PULLEY_VEHICLE_B_SERVO_DEFANG;
    Pulley_VEHICLE_C_Servo_1_Angle = PULLEY_VEHICLE_C_SERVO_1_DEFANG;
    Pulley_VEHICLE_C_Servo_2_Angle = PULLEY_VEHICLE_C_SERVO_2_DEFANG;
    //Init IO
    //VEHICLE A
    GPIO_PinMode(PULLEY_VEHICLE_A_AIN1_GROUP, PULLEY_VEHICLE_A_AIN1_CLK, PULLEY_VEHICLE_A_AIN1,
                 GPIO_Mode_OUT, GPIO_OType_PP, GPIO_Speed_100MHz, GPIO_PuPd_UP);
    GPIO_PinMode(PULLEY_VEHICLE_A_AIN2_GROUP, PULLEY_VEHICLE_A_AIN2_CLK, PULLEY_VEHICLE_A_AIN2,
                 GPIO_Mode_OUT, GPIO_OType_PP, GPIO_Speed_100MHz, GPIO_PuPd_UP);
    GPIO_PinMode(PULLEY_VEHICLE_A_PWMA_GROUP, PULLEY_VEHICLE_A_PWMA_CLK, PULLEY_VEHICLE_A_PWMA,
                 GPIO_Mode_OUT, GPIO_OType_PP, GPIO_Speed_100MHz, GPIO_PuPd_UP);
    GPIO_PinMode(PULLEY_VEHICLE_A_BIN1_GROUP, PULLEY_VEHICLE_A_BIN1_CLK, PULLEY_VEHICLE_A_BIN1,
                 GPIO_Mode_OUT, GPIO_OType_PP, GPIO_Speed_100MHz, GPIO_PuPd_UP);
    GPIO_PinMode(PULLEY_VEHICLE_A_BIN2_GROUP, PULLEY_VEHICLE_A_BIN2_CLK, PULLEY_VEHICLE_A_BIN2,
                 GPIO_Mode_OUT, GPIO_OType_PP, GPIO_Speed_100MHz, GPIO_PuPd_UP);
    GPIO_PinMode(PULLEY_VEHICLE_A_PWMB_GROUP, PULLEY_VEHICLE_A_PWMB_CLK, PULLEY_VEHICLE_A_PWMB,
                 GPIO_Mode_OUT, GPIO_OType_PP, GPIO_Speed_100MHz, GPIO_PuPd_UP);
    //VEHICLE B
    GPIO_PinMode(PULLEY_VEHICLE_B_AIN1_GROUP, PULLEY_VEHICLE_B_AIN1_CLK, PULLEY_VEHICLE_B_AIN1,
                 GPIO_Mode_OUT, GPIO_OType_PP, GPIO_Speed_100MHz, GPIO_PuPd_UP);
    GPIO_PinMode(PULLEY_VEHICLE_B_AIN2_GROUP, PULLEY_VEHICLE_B_AIN2_CLK, PULLEY_VEHICLE_B_AIN2,
                 GPIO_Mode_OUT, GPIO_OType_PP, GPIO_Speed_100MHz, GPIO_PuPd_UP);
    GPIO_PinMode(PULLEY_VEHICLE_B_PWMA_GROUP, PULLEY_VEHICLE_B_PWMA_CLK, PULLEY_VEHICLE_B_PWMA,
                 GPIO_Mode_OUT, GPIO_OType_PP, GPIO_Speed_100MHz, GPIO_PuPd_UP);
    GPIO_PinMode(PULLEY_VEHICLE_B_BIN1_GROUP, PULLEY_VEHICLE_B_BIN1_CLK, PULLEY_VEHICLE_B_BIN1,
                 GPIO_Mode_OUT, GPIO_OType_PP, GPIO_Speed_100MHz, GPIO_PuPd_UP);
    GPIO_PinMode(PULLEY_VEHICLE_B_BIN2_GROUP, PULLEY_VEHICLE_B_BIN2_CLK, PULLEY_VEHICLE_B_BIN2,
                 GPIO_Mode_OUT, GPIO_OType_PP, GPIO_Speed_100MHz, GPIO_PuPd_UP);
    GPIO_PinMode(PULLEY_VEHICLE_B_PWMB_GROUP, PULLEY_VEHICLE_B_PWMB_CLK, PULLEY_VEHICLE_B_PWMB,
                 GPIO_Mode_OUT, GPIO_OType_PP, GPIO_Speed_100MHz, GPIO_PuPd_UP);
    //VEHICLE C
    GPIO_PinMode(PULLEY_VEHICLE_C_AIN1_GROUP, PULLEY_VEHICLE_C_AIN1_CLK, PULLEY_VEHICLE_C_AIN1,
                 GPIO_Mode_OUT, GPIO_OType_PP, GPIO_Speed_100MHz, GPIO_PuPd_UP);
    GPIO_PinMode(PULLEY_VEHICLE_C_AIN2_GROUP, PULLEY_VEHICLE_C_AIN2_CLK, PULLEY_VEHICLE_C_AIN2,
                 GPIO_Mode_OUT, GPIO_OType_PP, GPIO_Speed_100MHz, GPIO_PuPd_UP);
    GPIO_PinMode(PULLEY_VEHICLE_C_PWMA_GROUP, PULLEY_VEHICLE_C_PWMA_CLK, PULLEY_VEHICLE_C_PWMA,
                 GPIO_Mode_OUT, GPIO_OType_PP, GPIO_Speed_100MHz, GPIO_PuPd_UP);
    GPIO_PinMode(PULLEY_VEHICLE_C_BIN1_GROUP, PULLEY_VEHICLE_C_BIN1_CLK, PULLEY_VEHICLE_C_BIN1,
                 GPIO_Mode_OUT, GPIO_OType_PP, GPIO_Speed_100MHz, GPIO_PuPd_UP);
    GPIO_PinMode(PULLEY_VEHICLE_C_BIN2_GROUP, PULLEY_VEHICLE_C_BIN2_CLK, PULLEY_VEHICLE_C_BIN2,
                 GPIO_Mode_OUT, GPIO_OType_PP, GPIO_Speed_100MHz, GPIO_PuPd_UP);
    GPIO_PinMode(PULLEY_VEHICLE_C_PWMB_GROUP, PULLEY_VEHICLE_C_PWMB_CLK, PULLEY_VEHICLE_C_PWMB,
                 GPIO_Mode_OUT, GPIO_OType_PP, GPIO_Speed_100MHz, GPIO_PuPd_UP);
    //Reset motor
    Pulley_VEHICLE_Run(PULLEY_VEHICLE_A, PULLEY_VEHICLE_IDLE);
    Pulley_VEHICLE_Run(PULLEY_VEHICLE_B, PULLEY_VEHICLE_IDLE);
    Pulley_VEHICLE_Run(PULLEY_VEHICLE_C, PULLEY_VEHICLE_IDLE);
    //Reset state
    Pulley_VEHICLE_A_State = PULLEY_VEHICLE_IDLE;
    Pulley_VEHICLE_B_State = PULLEY_VEHICLE_IDLE;
    Pulley_VEHICLE_C_State = PULLEY_VEHICLE_IDLE;
    return;
}

void Pulley_VEHICLE_Run(u8 vehicleID, u8 vehicleState)
{
    switch (vehicleID)
    {
    case PULLEY_VEHICLE_A:
    {
        if (vehicleState == PULLEY_VEHICLE_IDLE)
        {
            GPIO_WriteBit(PULLEY_VEHICLE_A_AIN1_GROUP, PULLEY_VEHICLE_A_AIN1, Bit_SET);
            GPIO_WriteBit(PULLEY_VEHICLE_A_AIN2_GROUP, PULLEY_VEHICLE_A_AIN2, Bit_SET);
            GPIO_WriteBit(PULLEY_VEHICLE_A_PWMA_GROUP, PULLEY_VEHICLE_A_PWMA, Bit_SET);
            GPIO_WriteBit(PULLEY_VEHICLE_A_BIN1_GROUP, PULLEY_VEHICLE_A_BIN1, Bit_SET);
            GPIO_WriteBit(PULLEY_VEHICLE_A_BIN2_GROUP, PULLEY_VEHICLE_A_BIN2, Bit_SET);
            GPIO_WriteBit(PULLEY_VEHICLE_A_PWMB_GROUP, PULLEY_VEHICLE_A_PWMB, Bit_SET);
            Pulley_VEHICLE_A_State = PULLEY_VEHICLE_IDLE;
        }
        else if (vehicleState == PULLEY_VEHICLE_FORWARD)
        {
            GPIO_WriteBit(PULLEY_VEHICLE_A_AIN1_GROUP, PULLEY_VEHICLE_A_AIN1, Bit_SET);
            GPIO_WriteBit(PULLEY_VEHICLE_A_AIN2_GROUP, PULLEY_VEHICLE_A_AIN2, Bit_RESET);
            GPIO_WriteBit(PULLEY_VEHICLE_A_PWMA_GROUP, PULLEY_VEHICLE_A_PWMA, Bit_SET);
            GPIO_WriteBit(PULLEY_VEHICLE_A_BIN1_GROUP, PULLEY_VEHICLE_A_BIN1, Bit_SET);
            GPIO_WriteBit(PULLEY_VEHICLE_A_BIN2_GROUP, PULLEY_VEHICLE_A_BIN2, Bit_RESET);
            GPIO_WriteBit(PULLEY_VEHICLE_A_PWMB_GROUP, PULLEY_VEHICLE_A_PWMB, Bit_SET);
            Pulley_VEHICLE_A_State = PULLEY_VEHICLE_FORWARD;
        }
        else if (vehicleState == PULLEY_VEHICLE_BACKWARD)
        {
            GPIO_WriteBit(PULLEY_VEHICLE_A_AIN1_GROUP, PULLEY_VEHICLE_A_AIN1, Bit_RESET);
            GPIO_WriteBit(PULLEY_VEHICLE_A_AIN2_GROUP, PULLEY_VEHICLE_A_AIN2, Bit_SET);
            GPIO_WriteBit(PULLEY_VEHICLE_A_PWMA_GROUP, PULLEY_VEHICLE_A_PWMA, Bit_SET);
            GPIO_WriteBit(PULLEY_VEHICLE_A_BIN1_GROUP, PULLEY_VEHICLE_A_BIN1, Bit_RESET);
            GPIO_WriteBit(PULLEY_VEHICLE_A_BIN2_GROUP, PULLEY_VEHICLE_A_BIN2, Bit_SET);
            GPIO_WriteBit(PULLEY_VEHICLE_A_PWMB_GROUP, PULLEY_VEHICLE_A_PWMB, Bit_SET);
            Pulley_VEHICLE_A_State = PULLEY_VEHICLE_BACKWARD;
        }
        else if (vehicleState == PULLEY_VEHICLE_TURNLEFT)
        {
            Pulley_VEHICLE_A_ServoAngle = (Pulley_VEHICLE_A_ServoAngle - 90 >= 0) ? (Pulley_VEHICLE_A_ServoAngle - 90) : 0;
            Pulley_SERVO_Write(PULLEY_VEHICLE_A_SERVO, Pulley_VEHICLE_A_ServoAngle);
            GPIO_WriteBit(PULLEY_VEHICLE_A_AIN1_GROUP, PULLEY_VEHICLE_A_AIN1, Bit_RESET);
            GPIO_WriteBit(PULLEY_VEHICLE_A_AIN2_GROUP, PULLEY_VEHICLE_A_AIN2, Bit_SET);
            GPIO_WriteBit(PULLEY_VEHICLE_A_PWMA_GROUP, PULLEY_VEHICLE_A_PWMA, Bit_SET);
            GPIO_WriteBit(PULLEY_VEHICLE_A_BIN1_GROUP, PULLEY_VEHICLE_A_BIN1, Bit_SET);
            GPIO_WriteBit(PULLEY_VEHICLE_A_BIN2_GROUP, PULLEY_VEHICLE_A_BIN2, Bit_RESET);
            GPIO_WriteBit(PULLEY_VEHICLE_A_PWMB_GROUP, PULLEY_VEHICLE_A_PWMB, Bit_SET);
            Pulley_VEHICLE_A_State = PULLEY_VEHICLE_TURNLEFT;
        }
        else if (vehicleState == PULLEY_VEHICLE_TURNRIGHT)
        {
            Pulley_VEHICLE_A_ServoAngle = (Pulley_VEHICLE_A_ServoAngle + 90 <= 180) ? (Pulley_VEHICLE_A_ServoAngle + 90) : 180;
            Pulley_SERVO_Write(PULLEY_VEHICLE_A_SERVO, Pulley_VEHICLE_A_ServoAngle);
            GPIO_WriteBit(PULLEY_VEHICLE_A_AIN1_GROUP, PULLEY_VEHICLE_A_AIN1, Bit_SET);
            GPIO_WriteBit(PULLEY_VEHICLE_A_AIN2_GROUP, PULLEY_VEHICLE_A_AIN2, Bit_RESET);
            GPIO_WriteBit(PULLEY_VEHICLE_A_PWMA_GROUP, PULLEY_VEHICLE_A_PWMA, Bit_SET);
            GPIO_WriteBit(PULLEY_VEHICLE_A_BIN1_GROUP, PULLEY_VEHICLE_A_BIN1, Bit_RESET);
            GPIO_WriteBit(PULLEY_VEHICLE_A_BIN2_GROUP, PULLEY_VEHICLE_A_BIN2, Bit_SET);
            GPIO_WriteBit(PULLEY_VEHICLE_A_PWMB_GROUP, PULLEY_VEHICLE_A_PWMB, Bit_SET);
            Pulley_VEHICLE_A_State = PULLEY_VEHICLE_TURNRIGHT;
        }
        return;
    }
    case PULLEY_VEHICLE_B:
    {
        if (vehicleState == PULLEY_VEHICLE_IDLE)
        {
            GPIO_WriteBit(PULLEY_VEHICLE_B_AIN1_GROUP, PULLEY_VEHICLE_B_AIN1, Bit_SET);
            GPIO_WriteBit(PULLEY_VEHICLE_B_AIN2_GROUP, PULLEY_VEHICLE_B_AIN2, Bit_SET);
            GPIO_WriteBit(PULLEY_VEHICLE_B_PWMA_GROUP, PULLEY_VEHICLE_B_PWMA, Bit_SET);
            GPIO_WriteBit(PULLEY_VEHICLE_B_BIN1_GROUP, PULLEY_VEHICLE_B_BIN1, Bit_SET);
            GPIO_WriteBit(PULLEY_VEHICLE_B_BIN2_GROUP, PULLEY_VEHICLE_B_BIN2, Bit_SET);
            GPIO_WriteBit(PULLEY_VEHICLE_B_PWMB_GROUP, PULLEY_VEHICLE_B_PWMB, Bit_SET);
            Pulley_VEHICLE_B_State = PULLEY_VEHICLE_IDLE;
        }
        else if (vehicleState == PULLEY_VEHICLE_FORWARD)
        {
            GPIO_WriteBit(PULLEY_VEHICLE_B_AIN1_GROUP, PULLEY_VEHICLE_B_AIN1, Bit_SET);
            GPIO_WriteBit(PULLEY_VEHICLE_B_AIN2_GROUP, PULLEY_VEHICLE_B_AIN2, Bit_RESET);
            GPIO_WriteBit(PULLEY_VEHICLE_B_PWMA_GROUP, PULLEY_VEHICLE_B_PWMA, Bit_SET);
            GPIO_WriteBit(PULLEY_VEHICLE_B_BIN1_GROUP, PULLEY_VEHICLE_B_BIN1, Bit_SET);
            GPIO_WriteBit(PULLEY_VEHICLE_B_BIN2_GROUP, PULLEY_VEHICLE_B_BIN2, Bit_RESET);
            GPIO_WriteBit(PULLEY_VEHICLE_B_PWMB_GROUP, PULLEY_VEHICLE_B_PWMB, Bit_SET);
            Pulley_VEHICLE_B_State = PULLEY_VEHICLE_FORWARD;
        }
        else if (vehicleState == PULLEY_VEHICLE_BACKWARD)
        {
            GPIO_WriteBit(PULLEY_VEHICLE_B_AIN1_GROUP, PULLEY_VEHICLE_B_AIN1, Bit_RESET);
            GPIO_WriteBit(PULLEY_VEHICLE_B_AIN2_GROUP, PULLEY_VEHICLE_B_AIN2, Bit_SET);
            GPIO_WriteBit(PULLEY_VEHICLE_B_PWMA_GROUP, PULLEY_VEHICLE_B_PWMA, Bit_SET);
            GPIO_WriteBit(PULLEY_VEHICLE_B_BIN1_GROUP, PULLEY_VEHICLE_B_BIN1, Bit_RESET);
            GPIO_WriteBit(PULLEY_VEHICLE_B_BIN2_GROUP, PULLEY_VEHICLE_B_BIN2, Bit_SET);
            GPIO_WriteBit(PULLEY_VEHICLE_B_PWMB_GROUP, PULLEY_VEHICLE_B_PWMB, Bit_SET);
            Pulley_VEHICLE_B_State = PULLEY_VEHICLE_BACKWARD;
        }
        else if (vehicleState == PULLEY_VEHICLE_TURNLEFT)
        {
            Pulley_VEHICLE_B_ServoAngle = (Pulley_VEHICLE_B_ServoAngle - 90 >= 0) ? (Pulley_VEHICLE_B_ServoAngle - 90) : 0;
            Pulley_SERVO_Write(PULLEY_VEHICLE_B_SERVO, Pulley_VEHICLE_B_ServoAngle);
            GPIO_WriteBit(PULLEY_VEHICLE_B_AIN1_GROUP, PULLEY_VEHICLE_B_AIN1, Bit_RESET);
            GPIO_WriteBit(PULLEY_VEHICLE_B_AIN2_GROUP, PULLEY_VEHICLE_B_AIN2, Bit_SET);
            GPIO_WriteBit(PULLEY_VEHICLE_B_PWMA_GROUP, PULLEY_VEHICLE_B_PWMA, Bit_SET);
            GPIO_WriteBit(PULLEY_VEHICLE_B_BIN1_GROUP, PULLEY_VEHICLE_B_BIN1, Bit_SET);
            GPIO_WriteBit(PULLEY_VEHICLE_B_BIN2_GROUP, PULLEY_VEHICLE_B_BIN2, Bit_RESET);
            GPIO_WriteBit(PULLEY_VEHICLE_B_PWMB_GROUP, PULLEY_VEHICLE_B_PWMB, Bit_SET);
            Pulley_VEHICLE_B_State = PULLEY_VEHICLE_TURNLEFT;
        }
        else if (vehicleState == PULLEY_VEHICLE_TURNRIGHT)
        {
            Pulley_VEHICLE_B_ServoAngle = (Pulley_VEHICLE_B_ServoAngle + 90 <= 180) ? (Pulley_VEHICLE_B_ServoAngle + 90) : 180;
            Pulley_SERVO_Write(PULLEY_VEHICLE_B_SERVO, Pulley_VEHICLE_B_ServoAngle);
            GPIO_WriteBit(PULLEY_VEHICLE_B_AIN1_GROUP, PULLEY_VEHICLE_B_AIN1, Bit_SET);
            GPIO_WriteBit(PULLEY_VEHICLE_B_AIN2_GROUP, PULLEY_VEHICLE_B_AIN2, Bit_RESET);
            GPIO_WriteBit(PULLEY_VEHICLE_B_PWMA_GROUP, PULLEY_VEHICLE_B_PWMA, Bit_SET);
            GPIO_WriteBit(PULLEY_VEHICLE_B_BIN1_GROUP, PULLEY_VEHICLE_B_BIN1, Bit_RESET);
            GPIO_WriteBit(PULLEY_VEHICLE_B_BIN2_GROUP, PULLEY_VEHICLE_B_BIN2, Bit_SET);
            GPIO_WriteBit(PULLEY_VEHICLE_B_PWMB_GROUP, PULLEY_VEHICLE_B_PWMB, Bit_SET);
            Pulley_VEHICLE_B_State = PULLEY_VEHICLE_TURNRIGHT;
        }
        return;
    }
    case PULLEY_VEHICLE_C:
    {
        if (vehicleState == PULLEY_VEHICLE_IDLE)
        {
            GPIO_WriteBit(PULLEY_VEHICLE_C_AIN1_GROUP, PULLEY_VEHICLE_C_AIN1, Bit_SET);
            GPIO_WriteBit(PULLEY_VEHICLE_C_AIN2_GROUP, PULLEY_VEHICLE_C_AIN2, Bit_SET);
            GPIO_WriteBit(PULLEY_VEHICLE_C_PWMA_GROUP, PULLEY_VEHICLE_C_PWMA, Bit_SET);
            GPIO_WriteBit(PULLEY_VEHICLE_C_BIN1_GROUP, PULLEY_VEHICLE_C_BIN1, Bit_SET);
            GPIO_WriteBit(PULLEY_VEHICLE_C_BIN2_GROUP, PULLEY_VEHICLE_C_BIN2, Bit_SET);
            GPIO_WriteBit(PULLEY_VEHICLE_C_PWMB_GROUP, PULLEY_VEHICLE_C_PWMB, Bit_SET);
            Pulley_VEHICLE_C_State = PULLEY_VEHICLE_IDLE;
        }
        else if (vehicleState == PULLEY_VEHICLE_FORWARD)
        {
            GPIO_WriteBit(PULLEY_VEHICLE_C_AIN1_GROUP, PULLEY_VEHICLE_C_AIN1, Bit_SET);
            GPIO_WriteBit(PULLEY_VEHICLE_C_AIN2_GROUP, PULLEY_VEHICLE_C_AIN2, Bit_RESET);
            GPIO_WriteBit(PULLEY_VEHICLE_C_PWMA_GROUP, PULLEY_VEHICLE_C_PWMA, Bit_SET);
            GPIO_WriteBit(PULLEY_VEHICLE_C_BIN1_GROUP, PULLEY_VEHICLE_C_BIN1, Bit_SET);
            GPIO_WriteBit(PULLEY_VEHICLE_C_BIN2_GROUP, PULLEY_VEHICLE_C_BIN2, Bit_RESET);
            GPIO_WriteBit(PULLEY_VEHICLE_C_PWMB_GROUP, PULLEY_VEHICLE_C_PWMB, Bit_SET);
            Pulley_VEHICLE_C_State = PULLEY_VEHICLE_FORWARD;
        }
        else if (vehicleState == PULLEY_VEHICLE_BACKWARD)
        {
            GPIO_WriteBit(PULLEY_VEHICLE_C_AIN1_GROUP, PULLEY_VEHICLE_C_AIN1, Bit_RESET);
            GPIO_WriteBit(PULLEY_VEHICLE_C_AIN2_GROUP, PULLEY_VEHICLE_C_AIN2, Bit_SET);
            GPIO_WriteBit(PULLEY_VEHICLE_C_PWMA_GROUP, PULLEY_VEHICLE_C_PWMA, Bit_SET);
            GPIO_WriteBit(PULLEY_VEHICLE_C_BIN1_GROUP, PULLEY_VEHICLE_C_BIN1, Bit_RESET);
            GPIO_WriteBit(PULLEY_VEHICLE_C_BIN2_GROUP, PULLEY_VEHICLE_C_BIN2, Bit_SET);
            GPIO_WriteBit(PULLEY_VEHICLE_C_PWMB_GROUP, PULLEY_VEHICLE_C_PWMB, Bit_SET);
            Pulley_VEHICLE_C_State = PULLEY_VEHICLE_BACKWARD;
        }
        else if (vehicleState == PULLEY_VEHICLE_TURNLEFT)
        {
            Pulley_VEHICLE_C_Servo_1_Angle = (Pulley_VEHICLE_C_Servo_1_Angle - 90 >= 0) ? (Pulley_VEHICLE_C_Servo_1_Angle - 90) : 0;
            Pulley_SERVO_Write(PULLEY_VEHICLE_C_SERVO_1, Pulley_VEHICLE_C_Servo_1_Angle);
            GPIO_WriteBit(PULLEY_VEHICLE_C_AIN1_GROUP, PULLEY_VEHICLE_C_AIN1, Bit_RESET);
            GPIO_WriteBit(PULLEY_VEHICLE_C_AIN2_GROUP, PULLEY_VEHICLE_C_AIN2, Bit_SET);
            GPIO_WriteBit(PULLEY_VEHICLE_C_PWMA_GROUP, PULLEY_VEHICLE_C_PWMA, Bit_SET);
            GPIO_WriteBit(PULLEY_VEHICLE_C_BIN1_GROUP, PULLEY_VEHICLE_C_BIN1, Bit_SET);
            GPIO_WriteBit(PULLEY_VEHICLE_C_BIN2_GROUP, PULLEY_VEHICLE_C_BIN2, Bit_RESET);
            GPIO_WriteBit(PULLEY_VEHICLE_C_PWMB_GROUP, PULLEY_VEHICLE_C_PWMB, Bit_SET);
            Pulley_VEHICLE_C_State = PULLEY_VEHICLE_TURNLEFT;
        }
        else if (vehicleState == PULLEY_VEHICLE_TURNRIGHT)
        {
            Pulley_VEHICLE_C_Servo_1_Angle = (Pulley_VEHICLE_C_Servo_1_Angle + 90 <= 180) ? (Pulley_VEHICLE_C_Servo_1_Angle + 90) : 180;
            Pulley_SERVO_Write(PULLEY_VEHICLE_C_SERVO_1, Pulley_VEHICLE_C_Servo_1_Angle);
            GPIO_WriteBit(PULLEY_VEHICLE_C_AIN1_GROUP, PULLEY_VEHICLE_C_AIN1, Bit_SET);
            GPIO_WriteBit(PULLEY_VEHICLE_C_AIN2_GROUP, PULLEY_VEHICLE_C_AIN2, Bit_RESET);
            GPIO_WriteBit(PULLEY_VEHICLE_C_PWMA_GROUP, PULLEY_VEHICLE_C_PWMA, Bit_SET);
            GPIO_WriteBit(PULLEY_VEHICLE_C_BIN1_GROUP, PULLEY_VEHICLE_C_BIN1, Bit_RESET);
            GPIO_WriteBit(PULLEY_VEHICLE_C_BIN2_GROUP, PULLEY_VEHICLE_C_BIN2, Bit_SET);
            GPIO_WriteBit(PULLEY_VEHICLE_C_PWMB_GROUP, PULLEY_VEHICLE_C_PWMB, Bit_SET);
            Pulley_VEHICLE_C_State = PULLEY_VEHICLE_TURNRIGHT;
        }
        return;
    }
    }
    return;
}

void Pulley_VEHICLE_C_HookRotate()
{
    Pulley_VEHICLE_C_Servo_2_Angle = (Pulley_VEHICLE_C_Servo_2_Angle + 90 > 180) ? 0 : (Pulley_VEHICLE_C_Servo_2_Angle + 90);
    Pulley_SERVO_Write(PULLEY_VEHICLE_C_SERVO_2, Pulley_VEHICLE_C_Servo_2_Angle);
    return;
}
